# Generated by Django 4.0.5 on 2022-11-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_likesandcomments_post_usersfolowing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likesandcomments',
            old_name='comments',
            new_name='postID',
        ),
    ]
