# Generated by Django 4.0.5 on 2022-11-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.CharField(max_length=84),
        ),
    ]
