# Generated by Django 4.0.5 on 2022-12-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.TextField()),
                ('likes', models.IntegerField()),
                ('likedBy', models.CharField(max_length=84)),
            ],
        ),
        migrations.DeleteModel(
            name='likesAndComments',
        ),
    ]
